// <auto-generated />
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(GameWikiDBContext))]
    [Migration("20220619172331_GamewikiDBTest")]
    partial class GamewikiDBTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmmoWeapon", b =>
                {
                    b.Property<int>("AmmoID")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsID")
                        .HasColumnType("int");

                    b.HasKey("AmmoID", "WeaponsID");

                    b.HasIndex("WeaponsID");

                    b.ToTable("AmmoWeapon");
                });

            modelBuilder.Entity("BusinessLayer.Ammo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Damage")
                        .HasColumnType("float");

                    b.Property<int>("DamageType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Ammo");
                });

            modelBuilder.Entity("BusinessLayer.Enemy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Armor")
                        .HasColumnType("float");

                    b.Property<int>("Behaviour")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Health")
                        .HasColumnType("float");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeakAgainst")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("BusinessLayer.Weapon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("DamageMultiplier")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("EnemyWeapon", b =>
                {
                    b.Property<int>("EnemiesID")
                        .HasColumnType("int");

                    b.Property<int>("WeaponsID")
                        .HasColumnType("int");

                    b.HasKey("EnemiesID", "WeaponsID");

                    b.HasIndex("WeaponsID");

                    b.ToTable("EnemyWeapon");
                });

            modelBuilder.Entity("AmmoWeapon", b =>
                {
                    b.HasOne("BusinessLayer.Ammo", null)
                        .WithMany()
                        .HasForeignKey("AmmoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnemyWeapon", b =>
                {
                    b.HasOne("BusinessLayer.Enemy", null)
                        .WithMany()
                        .HasForeignKey("EnemiesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessLayer.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
